modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Lykrast/bypowderandsteel/issues"
license="All Rights Reserved https://github.com/Lykrast/ByPowderAndSteel/blob/main/LICENSE"

[[mods]]
modId="bypowderandsteel"
version="${file.jarVersion}"
displayName="By Powder and Steel"
displayURL="https://modrinth.com/mod/by-powder-and-steel"
credits=""
authors="Lykrast"
description='''
Mob addon for Guns Without Roses.
'''

[[dependencies.bypowderandsteel]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bypowderandsteel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.bypowderandsteel]]
    modId="gunswithoutroses"
    mandatory=true
    versionRange="[1.20.1-2.5.0,)"
    ordering="AFTER"
    side="BOTH"