modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Lykrast/bypowderandsteel/issues"
license="All Rights Reserved https://github.com/Lykrast/ByPowderAndSteel/blob/main/LICENSE"

[[mods]]
modId="bypowderandsteel"
version="${file.jarVersion}"
displayName="By Powder and Steel"
displayURL="https://modrinth.com/mod/by-powder-and-steel"
logoFile="iconbyzaya.png"
credits="Zaya https://zaya.gallery/ that I commissioned for the mod icon, freesound.org for all the creative common sounds"
authors="Lykrast"
description='''
Addon for Guns Without Roses. Adds a variety of biome-specific mobs, some of them wearing guns that you can craft for yourself!
'''

[[dependencies.bypowderandsteel]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bypowderandsteel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.bypowderandsteel]]
    modId="gunswithoutroses"
    mandatory=true
    versionRange="[1.20.1-2.5.0,)"
    ordering="AFTER"
    side="BOTH"