modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Lykrast/bypowderandsteel/issues"
license="MIT License for code https://github.com/Lykrast/bypowderandsteel/blob/head/LICENSE"

[[mods]]
modId="bypowderandsteel"
version="${file.jarVersion}"
displayName="By Powder And Steel"
displayURL="https://modrinth.com/mod/bpas"
credits=""
authors="Lykrast"
description='''
Mob addon for Guns Without Roses.
'''

[[dependencies.bypowderandsteel]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bypowderandsteel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.bypowderandsteel]]
    modId="gunswithoutroses"
    mandatory=true
    versionRange="[1.20.1-2.1.0,)"
    ordering="AFTER"
    side="BOTH"